/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "NGAP-rel16.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -gen-PER -D ngap`
 */

#ifndef	_ASN_NGAP_ProtocolIE_Container_H_
#define	_ASN_NGAP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_NGAP_PDUSessionResourceSetupRequestIEs;
struct ASN_NGAP_PDUSessionResourceSetupResponseIEs;
struct ASN_NGAP_PDUSessionResourceReleaseCommandIEs;
struct ASN_NGAP_PDUSessionResourceReleaseResponseIEs;
struct ASN_NGAP_PDUSessionResourceModifyRequestIEs;
struct ASN_NGAP_PDUSessionResourceModifyResponseIEs;
struct ASN_NGAP_PDUSessionResourceNotifyIEs;
struct ASN_NGAP_PDUSessionResourceModifyIndicationIEs;
struct ASN_NGAP_PDUSessionResourceModifyConfirmIEs;
struct ASN_NGAP_InitialContextSetupRequestIEs;
struct ASN_NGAP_InitialContextSetupResponseIEs;
struct ASN_NGAP_InitialContextSetupFailureIEs;
struct ASN_NGAP_UEContextReleaseRequest_IEs;
struct ASN_NGAP_UEContextReleaseCommand_IEs;
struct ASN_NGAP_UEContextReleaseComplete_IEs;
struct ASN_NGAP_UEContextResumeRequestIEs;
struct ASN_NGAP_UEContextResumeResponseIEs;
struct ASN_NGAP_UEContextResumeFailureIEs;
struct ASN_NGAP_UEContextSuspendRequestIEs;
struct ASN_NGAP_UEContextSuspendResponseIEs;
struct ASN_NGAP_UEContextSuspendFailureIEs;
struct ASN_NGAP_UEContextModificationRequestIEs;
struct ASN_NGAP_UEContextModificationResponseIEs;
struct ASN_NGAP_UEContextModificationFailureIEs;
struct ASN_NGAP_RRCInactiveTransitionReportIEs;
struct ASN_NGAP_RetrieveUEInformationIEs;
struct ASN_NGAP_UEInformationTransferIEs;
struct ASN_NGAP_RANCPRelocationIndicationIEs;
struct ASN_NGAP_HandoverRequiredIEs;
struct ASN_NGAP_HandoverCommandIEs;
struct ASN_NGAP_HandoverPreparationFailureIEs;
struct ASN_NGAP_HandoverRequestIEs;
struct ASN_NGAP_HandoverRequestAcknowledgeIEs;
struct ASN_NGAP_HandoverFailureIEs;
struct ASN_NGAP_HandoverNotifyIEs;
struct ASN_NGAP_PathSwitchRequestIEs;
struct ASN_NGAP_PathSwitchRequestAcknowledgeIEs;
struct ASN_NGAP_PathSwitchRequestFailureIEs;
struct ASN_NGAP_HandoverCancelIEs;
struct ASN_NGAP_HandoverCancelAcknowledgeIEs;
struct ASN_NGAP_HandoverSuccessIEs;
struct ASN_NGAP_UplinkRANEarlyStatusTransferIEs;
struct ASN_NGAP_DownlinkRANEarlyStatusTransferIEs;
struct ASN_NGAP_UplinkRANStatusTransferIEs;
struct ASN_NGAP_DownlinkRANStatusTransferIEs;
struct ASN_NGAP_PagingIEs;
struct ASN_NGAP_InitialUEMessage_IEs;
struct ASN_NGAP_DownlinkNASTransport_IEs;
struct ASN_NGAP_UplinkNASTransport_IEs;
struct ASN_NGAP_NASNonDeliveryIndication_IEs;
struct ASN_NGAP_RerouteNASRequest_IEs;
struct ASN_NGAP_NGSetupRequestIEs;
struct ASN_NGAP_NGSetupResponseIEs;
struct ASN_NGAP_NGSetupFailureIEs;
struct ASN_NGAP_RANConfigurationUpdateIEs;
struct ASN_NGAP_RANConfigurationUpdateAcknowledgeIEs;
struct ASN_NGAP_RANConfigurationUpdateFailureIEs;
struct ASN_NGAP_AMFConfigurationUpdateIEs;
struct ASN_NGAP_AMFConfigurationUpdateAcknowledgeIEs;
struct ASN_NGAP_AMFConfigurationUpdateFailureIEs;
struct ASN_NGAP_AMFStatusIndicationIEs;
struct ASN_NGAP_NGResetIEs;
struct ASN_NGAP_NGResetAcknowledgeIEs;
struct ASN_NGAP_ErrorIndicationIEs;
struct ASN_NGAP_OverloadStartIEs;
struct ASN_NGAP_OverloadStopIEs;
struct ASN_NGAP_UplinkRANConfigurationTransferIEs;
struct ASN_NGAP_DownlinkRANConfigurationTransferIEs;
struct ASN_NGAP_WriteReplaceWarningRequestIEs;
struct ASN_NGAP_WriteReplaceWarningResponseIEs;
struct ASN_NGAP_PWSCancelRequestIEs;
struct ASN_NGAP_PWSCancelResponseIEs;
struct ASN_NGAP_PWSRestartIndicationIEs;
struct ASN_NGAP_PWSFailureIndicationIEs;
struct ASN_NGAP_DownlinkUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_UplinkUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_UplinkNonUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_TraceStartIEs;
struct ASN_NGAP_TraceFailureIndicationIEs;
struct ASN_NGAP_DeactivateTraceIEs;
struct ASN_NGAP_CellTrafficTraceIEs;
struct ASN_NGAP_LocationReportingControlIEs;
struct ASN_NGAP_LocationReportingFailureIndicationIEs;
struct ASN_NGAP_LocationReportIEs;
struct ASN_NGAP_UETNLABindingReleaseRequestIEs;
struct ASN_NGAP_UERadioCapabilityInfoIndicationIEs;
struct ASN_NGAP_UERadioCapabilityCheckRequestIEs;
struct ASN_NGAP_UERadioCapabilityCheckResponseIEs;
struct ASN_NGAP_SecondaryRATDataUsageReportIEs;
struct ASN_NGAP_UplinkRIMInformationTransferIEs;
struct ASN_NGAP_DownlinkRIMInformationTransferIEs;
struct ASN_NGAP_ConnectionEstablishmentIndicationIEs;
struct ASN_NGAP_UERadioCapabilityIDMappingRequestIEs;
struct ASN_NGAP_UERadioCapabilityIDMappingResponseIEs;
struct ASN_NGAP_AMFCPRelocationIndicationIEs;
struct ASN_NGAP_PDUSessionResourceModifyRequestTransferIEs;
struct ASN_NGAP_PDUSessionResourceSetupRequestTransferIEs;

/* ASN_NGAP_ProtocolIE-Container */
typedef struct ASN_NGAP_ProtocolIE_Container_9622P0 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P0_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P1 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P1_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P2 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P2_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P3 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P3_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P4 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P4_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P5 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P5_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P6 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P6_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P7 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P7_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P8 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P8_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P9 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P9_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P10 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P10_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P11 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P11_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P12 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P12_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P13 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P13_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P14 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P14_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P15 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextResumeRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P15_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P16 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextResumeResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P16_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P17 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextResumeFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P17_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P18 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextSuspendRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P18_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P19 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextSuspendResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P19_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P20 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextSuspendFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P20_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P21 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P21_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P22 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P22_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P23 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P23_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P24 {
	A_SEQUENCE_OF(struct ASN_NGAP_RRCInactiveTransitionReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P24_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P25 {
	A_SEQUENCE_OF(struct ASN_NGAP_RetrieveUEInformationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P25_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P26 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P26_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P27 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P27_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P28 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P28_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P29 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P29_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P30 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P30_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P31 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P31_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P32 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P32_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P33 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P33_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P34 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P34_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P35 {
	A_SEQUENCE_OF(struct ASN_NGAP_PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P35_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P36 {
	A_SEQUENCE_OF(struct ASN_NGAP_PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P36_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P37 {
	A_SEQUENCE_OF(struct ASN_NGAP_PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P37_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P38 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P38_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P39 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P39_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P40 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverSuccessIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P40_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P41 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P41_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P42 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P42_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P43 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P43_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P44 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P44_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P45 {
	A_SEQUENCE_OF(struct ASN_NGAP_PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P45_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P46 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P46_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P47 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P47_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P48 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P48_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P49 {
	A_SEQUENCE_OF(struct ASN_NGAP_NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P49_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P50 {
	A_SEQUENCE_OF(struct ASN_NGAP_RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P50_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P51 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P51_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P52 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P52_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P53 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P53_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P54 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P54_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P55 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P55_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P56 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P56_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P57 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P57_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P58 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P58_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P59 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P59_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P60 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P60_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P61 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P61_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P62 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P62_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P63 {
	A_SEQUENCE_OF(struct ASN_NGAP_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P63_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P64 {
	A_SEQUENCE_OF(struct ASN_NGAP_OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P64_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P65 {
	A_SEQUENCE_OF(struct ASN_NGAP_OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P65_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P66 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P66_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P67 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P67_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P68 {
	A_SEQUENCE_OF(struct ASN_NGAP_WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P68_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P69 {
	A_SEQUENCE_OF(struct ASN_NGAP_WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P69_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P70 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P70_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P71 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P71_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P72 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P72_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P73 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P73_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P74 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P74_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P75 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P75_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P76 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P76_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P77 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P77_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P78 {
	A_SEQUENCE_OF(struct ASN_NGAP_TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P78_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P79 {
	A_SEQUENCE_OF(struct ASN_NGAP_TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P79_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P80 {
	A_SEQUENCE_OF(struct ASN_NGAP_DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P80_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P81 {
	A_SEQUENCE_OF(struct ASN_NGAP_CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P81_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P82 {
	A_SEQUENCE_OF(struct ASN_NGAP_LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P82_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P83 {
	A_SEQUENCE_OF(struct ASN_NGAP_LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P83_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P84 {
	A_SEQUENCE_OF(struct ASN_NGAP_LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P84_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P85 {
	A_SEQUENCE_OF(struct ASN_NGAP_UETNLABindingReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P85_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P86 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P86_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P87 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P87_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P88 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityCheckResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P88_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P89 {
	A_SEQUENCE_OF(struct ASN_NGAP_SecondaryRATDataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P89_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P90 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P90_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P91 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P91_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P92 {
	A_SEQUENCE_OF(struct ASN_NGAP_ConnectionEstablishmentIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P92_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P93 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityIDMappingRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P93_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P94 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityIDMappingResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P94_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P95 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P95_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P96 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P96_t;
typedef struct ASN_NGAP_ProtocolIE_Container_9622P97 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceSetupRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_9622P97_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P0;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P0_1[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P1;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P1_3[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P2;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P2_5[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P3;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P3_7[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P4;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P4_9[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P5;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P5_11[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P6;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P6_13[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P7;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P7_15[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P8;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P8_17[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P9;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P9_19[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P10;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P10_21[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P11;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P11_23[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P12;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P12_25[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P13;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P13_27[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P14;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P14_29[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P15;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P15_31[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P16;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P16_33[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P17;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P17_35[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P18;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P18_37[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P19;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P19_39[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P20;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P20_41[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P21;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P21_43[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P22;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P22_45[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P23;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P23_47[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P24;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P24_49[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P25;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P25_51[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P26;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P26_53[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P27;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P27_55[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P28;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P28_57[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P29;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P29_59[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P30;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P30_61[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P31;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P31_63[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P32;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P32_65[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P33;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P33_67[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P34;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P34_69[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P35;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P35_71[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P36;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P36_73[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P37;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P37_75[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P38;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P38_77[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P39;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P39_79[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P40;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P40_81[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P41;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P41_83[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P42;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P42_85[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P43;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P43_87[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P44;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P44_89[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P45;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P45_91[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P46;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P46_93[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P47;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P47_95[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P48;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P48_97[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P49;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P49_99[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P50;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P50_101[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P51;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P51_103[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P52;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P52_105[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P53;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P53_107[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P54;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P54_109[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P55;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P55_111[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P56;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P56_113[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P57;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P57_115[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P58;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P58_117[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P59;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P59_119[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P60;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P60_121[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P61;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P61_123[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P62;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P62_125[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P63;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P63_127[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P64;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P64_129[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P65;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P65_131[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P66;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P66_133[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P67;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P67_135[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P68;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P68_137[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P69;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P69_139[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P70;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P70_141[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P71;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P71_143[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P72;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P72_145[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P73;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P73_147[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P74;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P74_149[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P75;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P75_151[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P76;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P76_153[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P77;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P77_155[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P78;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P78_157[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P79;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P79_159[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P80;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P80_161[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P81;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P81_163[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P82;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P82_165[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P83;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P83_167[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P84;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P84_169[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P85;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P85_171[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P86;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P86_173[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P87;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P87_175[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P88;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P88_177[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P89;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P89_179[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P90;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P90_181[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P91;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P91_183[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P92;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P92_185[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P93;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P93_187[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P94;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P94_189[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P95;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P95_specs_191;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P95_191[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P96;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P96_specs_193;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P96_193[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_9622P97;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_9622P97_specs_195;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_9622P97_195[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_9622P97_constr_195;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_NGAP_ProtocolIE_Container_H_ */
#include <asn_internal.h>
